### ISSUE TITLE
Same situation with 1.1.10

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#15]
HB goes down:

30.10.2020, 06:40:39 [Genie Wohnzimmer] Genie Wohnzimmer :: ERROR :: api/account/hubs :: setActiveState() > Error: Parsing error : Unexpected token < in JSON at position 0, body= 
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
30.10.2020, 06:40:39 Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:12:19
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:381:9
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
30.10.2020, 06:40:39 Got SIGTERM, shutting down Bridge...

**Comment by myluna08** [comment]
Dear @Christian-CFP new 1.1.11 published, hope this works

**Comment by Christian-CFP** [comment]
Happy Halloween! But I am sorry:

31.10.2020, 10:01:31 [Genie Zoe] Genie Zoe :: ERROR :: api/account/hubs :: setFanSpeed() > Error: Parsing error : Unexpected token < in JSON at position 0, body= 
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
31.10.2020, 10:01:31 Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:12:19
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:423:17
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
31.10.2020, 10:01:31 Got SIGTERM, shutting down Bridge...

**Comment by Christian-CFP** [comment]
In addition to that.

2.11.2020, 06:18:20 [Genie Wohnzimmer] Genie Wohnzimmer getCurrentState => 404 :: null
2.11.2020, 06:18:20 [Genie Zoe] Genie Zoe getCurrentState => 404 :: null
2.11.2020, 06:18:20 [Genie Nuria] Genie Nuria getCurrentState => 404 :: null
2.11.2020, 06:18:32 [Genie Wohnzimmer] Genie Wohnzimmer getCurrentState => 404 :: null
2.11.2020, 06:18:32 [Genie Zoe] Genie Zoe getCurrentState => 404 :: null
2.11.2020, 06:18:32 [Genie Nuria] Genie Nuria getCurrentState => 404 :: null
2.11.2020, 06:18:40 [Genie Zoe] Genie Zoe getCurrentState => 404 :: null
2.11.2020, 06:18:40 [Genie Nuria] Genie Nuria getCurrentState => 404 :: null
2.11.2020, 06:18:40 [Genie Wohnzimmer] Genie Wohnzimmer getCurrentState => 404 :: null
2.11.2020, 06:18:42 [Genie Zoe] Genie Zoe getCurrentState => 404 :: null
2.11.2020, 06:18:42 [Genie Nuria] Genie Nuria getCurrentState => 404 :: null
2.11.2020, 06:18:42 [Genie Wohnzimmer] Genie Wohnzimmer getCurrentState => 404 :: null
2.11.2020, 06:19:56 [Genie Zoe] Genie Zoe getCurrentState => 404 :: null
2.11.2020, 06:19:56 [Genie Wohnzimmer] Genie Wohnzimmer getCurrentState => 404 :: null
2.11.2020, 06:19:56 [Genie Nuria] Genie Nuria getCurrentState => 404 :: null
2.11.2020, 06:20:15 [Genie Nuria] Genie Nuria getCurrentState => 404 :: null
2.11.2020, 06:20:15 [Genie Zoe] Genie Zoe getCurrentState => 404 :: null
2.11.2020, 06:20:15 [Genie Wohnzimmer] Genie Wohnzimmer getCurrentState => 404 :: null

I get a 404. And if this is like that, no HB device will show up in HomeKit.
So I had to delete the genies from the config to get it work again.

**Comment by myluna08** [comment]
@Christian-CFP 1.1.12 will be avoid this error

**Comment by Christian-CFP** [comment]
1.1.12:

2.11.2020, 14:00:20 [Genie Nuria] Genie Nuria :: ERROR :: api/account/hubs :: getCurrentState() > Error: connect ETIMEDOUT 46.22.190.75:443
2.11.2020, 14:00:20 [Genie Nuria] That means GENIE servers are down!
2.11.2020, 14:00:20 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:330:25
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2.11.2020, 14:00:20 Got SIGTERM, shutting down Bridge...

**Comment by myluna08** [comment]
Ups! solved 1.1.13

**Comment by Christian-CFP** [comment]
Hi, stil the same:

5.11.2020, 06:43:01 [Genie Zoe] Genie Zoe :: ERROR :: api/account/hubs :: getCurrentState() > Error: read ECONNRESET
5.11.2020, 06:43:01 [Genie Zoe] That means GENIE servers are down!
5.11.2020, 06:43:01 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:330:25
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
5.11.2020, 06:43:01 Got SIGTERM, shutting down Bridge...

**Comment by myluna08** [comment]
Solved in 1.1.14
