### ISSUE TITLE
ERROR in V 1.1.4

### ISSUE THREAD

**Issue by sensationunddesign** [myluna08/homebridge-rituals#20]
[1/16/2021, 2:48:24 PM] Error: EACCES: permission denied, open '/root/.homebridge/.uix-rituals-secrets_'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Storage._load (/homebridge/node_modules/homebridge-rituals/node_modules/node-storage/index.js:169:26)
    at new Storage (/homebridge/node_modules/homebridge-rituals/node_modules/node-storage/index.js:31:21)
    at new RitualsAccessory (/homebridge/node_modules/homebridge-rituals/index.js:33:20)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:355:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)

have no idea what's the problem. Tried to install but not chance - always makes a restart fo the home bridge…

**Comment by myluna08** [comment]
Dear @sensationunddesign , did you run your homebridge as SUDO ?? you can verify this in your homebridge UI settings.

**Comment by sensationunddesign** [comment]
@myluna08 - thanx for replying. What do you mean about run with sudo…ich have already some plugins running in homebridge. I did the installation with the plugin…

**Comment by myluna08** [comment]
@sensationunddesign in you homebridge go to ui settings, look at this image
![Captura de pantalla 2021-01-17 a las 12 43 23](https://user-images.githubusercontent.com/59629971/104839463-9fed6600-58c1-11eb-9623-0cdc98a05645.png)

**Comment by sensationunddesign** [comment]
@myluna08 - don't have this option…
<img width="786" alt="Bildschirmfoto 2021-01-17 um 12 45 39" src="https://user-images.githubusercontent.com/76649467/104839547-138f7300-58c2-11eb-9a18-c0b79adc77ae.png">

**Comment by myluna08** [comment]
@sensationunddesign please report, homebridge version, nodejs version and npm version

**Comment by sensationunddesign** [comment]
@myluna08 
HB: v1.2.5
Node.js Version | v14.15.3
NPM : v6.14.9

**Comment by myluna08** [comment]
@sensationunddesign verify in your config.json if you have sudo: true, if not change or add this value and restart your homebrige.

`"platforms": [
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "sudo": true
    }
]`

**Comment by sensationunddesign** [comment]
i have updated this, still same error…
[1/17/2021, 1:08:05 PM] [Rituals] Initializing Rituals accessory...
[1/17/2021, 1:08:05 PM] Error: EACCES: permission denied, open '/root/.homebridge/.uix-rituals-secrets_'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Storage._load (/homebridge/node_modules/homebridge-rituals/node_modules/node-storage/index.js:169:26)
    at new Storage (/homebridge/node_modules/homebridge-rituals/node_modules/node-storage/index.js:31:21)
    at new RitualsAccessory (/homebridge/node_modules/homebridge-rituals/index.js:33:20)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:355:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
[1/17/2021, 1:08:05 PM] Got SIGTERM, shutting down Homebridge...

**Comment by myluna08** [comment]
@sensationunddesign delete his file .uix-rituals-secrets_ and restart your homebridge again.

**Comment by sensationunddesign** [comment]
ok, I can't find this file.…there is only a .uix-secrets
<img width="912" alt="Bildschirmfoto 2021-01-17 um 13 13 32" src="https://user-images.githubusercontent.com/76649467/104840142-da590200-58c5-11eb-9b36-fc96dc884a97.png">

**Comment by myluna08** [comment]
![Captura de pantalla 2021-01-17 a las 13 24 39](https://user-images.githubusercontent.com/59629971/104842791-60c21380-58c7-11eb-8670-cf97c5389081.png)
@sensationunddesign for some reason your homebridge wants to open .uix-rituals-secrets under the .homebrige on root folder, not on normal homebridge user folder, this thing could be because of your installation. Verify if under homebrige user there are a .homebrige folder and inside if there are .uix-rituals-secrets_, if not just create file doing a touch.
`touch .uix-rituals-secrets_`

**Comment by sensationunddesign** [comment]
<img width="1238" alt="Bildschirmfoto 2021-01-17 um 13 33 31" src="https://user-images.githubusercontent.com/76649467/104842974-a29f8980-58c8-11eb-9152-bc928f3c01ad.png">
<img width="567" alt="Bildschirmfoto 2021-01-17 um 13 30 13" src="https://user-images.githubusercontent.com/76649467/104842909-29079b80-58c8-11eb-94e6-794efc4e7dbd.png">
admin@SERVER:/volume1/docker/homebridge$ ls -la
total 956
drwxr-xr-x  9 admin users   4096 Jan 17 13:18 .
drwxrwxrwx+ 5   999   999   4096 Jan 12 08:23 ..
drwxr-xr-x  2 admin users   4096 Nov 26 10:44 accessories
-rw-r--r--  1 admin users    359 Nov 26 08:24 auth.json
drwxr-xr-x  4 admin users   4096 Nov 27 01:15 backups
-rw-r--r--  1 admin users   3861 Jan 17 13:18 config.json
-rw-r--r--  1 admin users     81 Nov 26 08:21 .docker.env
-rw-r--r--  1 admin users   1356 Dec 28 16:01 eufy-security-credentials.json
-rw-r--r--  1 admin users 775077 Jan 17 13:28 homebridge.log
drwxr-xr-x  2 admin users   4096 Nov 26 16:37 .homebridge-nukiio
drwxr-xr-x  2 admin users   4096 Nov 26 08:21 logs
drwxr-xr-x  8 admin users   4096 Jan 16 14:41 node_modules
drwxrwxrwx  2 admin users   4096 Nov 26 16:48 nuki-cache
-rw-r--r--  1 admin users    309 Jan 16 14:41 package.json
-rw-r--r--  1 admin users 125425 Jan 16 14:41 package-lock.json
drwxr-xr-x  2 admin users   4096 Nov 26 08:22 persist
-rwxr-xr-x  1 admin users    573 Nov 26 08:21 startup.sh
-rw-r--r--  1 admin users   1103 Jan 17 11:58 .uix-dashboard.json
-rw-r--r--  1 admin users     81 Nov 26 08:22 .uix-secrets


is this correct or do I have to choose another folder? Tried this, but same problem…

**Comment by sensationunddesign** [comment]
@myluna08 - any idea?

**Comment by myluna08** [comment]
Dear @sensationunddesign I think the problem was on your docker installation. Plugin search for /root/.homebridge/ folder, try to create manually the file in this folder. Create the file using touch, assign correct permissions as I can see in your installation assigned to admin:users using chown and to verify all users can access to the file, then execute a chmod +x to the file.

`touch .uix-rituals-secrets_`
`chown admin:users .uix-rituals-secrets_`
`chmod +x .uix-rituals-secrets_`

`Error: EACCES: permission denied, open '/root/.homebridge/.uix-rituals-secrets_'
at Object.openSync (fs.js:476:3)`

**Comment by myluna08** [comment]
@sensationunddesign what about my last comment ??

**Comment by sensationunddesign** [comment]
hi @myluna08 , 
thx für your reply. still not working. would be a remote session possible?

**Comment by myluna08** [comment]
Sorry for the delay of answer, still have the problem?
