### ISSUE TITLE
Issue with Genies that are already on

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#26]
Hi I found out that when genies are turned manually on and a automation kicks in Homebridge stops working.

Manually ON 25.2.2021, 09:43:57 [Genie 1] Genie 1 :: Set ActiveState to => true
Manually ON 25.2.2021, 09:59:05 [Genie 2] Genie 2 :: Set ActiveState to => true
Manually ON 25.2.2021, 09:59:05 [Genie 3] Genie 3 :: Set ActiveState to => true
Automation 25.2.2021, 10:00:00 [Genie 2] Genie 2 :: Set ActiveState to => true
Automation 25.2.2021, 10:00:00 [Genie 2] Genie 2 :: Set FanSpeed to => 2
Automation 25.2.2021, 10:00:01 [Genie 1] Genie 1 :: Set FanSpeed to => 2
Automation 25.2.2021, 10:00:01 [Genie 1] Genie 1 :: Set ActiveState to => true
Automation 25.2.2021, 10:00:07 [Genie 3] Genie 3 :: Set ActiveState to => true
Automation 25.2.2021, 10:00:07 [Genie 3] Genie 3 :: Set FanSpeed to => 2
25.2.2021, 10:01:27 [Genie 3] Genie 3 :: ERROR :: api/account/hubs :: getCurrentState() > Error: connect ETIMEDOUT 37.97.128.129:443
25.2.2021, 10:01:27 [Genie 3] That means GENIE servers are down!
25.2.2021, 10:01:27 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:330:25
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
25.2.2021, 10:01:27 [Genie 2] Genie 2 :: ERROR :: api/account/hubs :: getCurrentState() > Error: connect ETIMEDOUT 37.97.128.129:443
25.2.2021, 10:01:27 [Genie 2] That means GENIE servers are down!
25.2.2021, 10:01:27 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:330:25
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
25.2.2021, 10:01:27 Got SIGTERM, shutting down Bridge...
25.2.2021, 10:01:28 [TV] INFO - shutdown
25.2.2021, 10:01:28 [FritzPlatform] Callmonitor: Shutting down...
25.2.2021, 10:01:28 [TV] INFO - shutdown
25.2.2021, 10:01:28 [FritzPlatform] Callmonitor: Shutting down...
25.2.2021, 10:01:28 [FritzPlatform] Callmonitor: Connection closed!
25.2.2021, 10:01:28 [Refresh Services] socket hang up
25.2.2021, 10:01:28 [Refresh Services] socket hang up
25.2.2021, 10:01:31 [Hue] goodbye
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
25.2.2021, 10:01:32 [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
...

**Comment by Christian-CFP** [comment]
Ok I see, you do not care anymore... shame.
