### ISSUE TITLE
Request has been deprecated error

### ISSUE THREAD

**Issue by marked80** [myluna08/homebridge-rituals#30]
Hi,

Since today my rituals plugin constantly is running in error.

[homebridge-rituals] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[4/24/2021, 6:00:59 PM] TypeError: Cannot read property 'hash' of undefined
    at /homebridge/node_modules/homebridge-rituals/index.js:235:47
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-rituals/index.js:234:43
    at Object.parseBody (/homebridge/node_modules/homebridge-rituals/node_modules/request-json/main.js:74:12)
    at Request._callback (/homebridge/node_modules/homebridge-rituals/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/homebridge/node_modules/homebridge-rituals/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-rituals/node_modules/request-json/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-rituals/node_modules/request-json/node_modules/request/request.js:1083:12)
[4/24/2021, 6:00:59 PM] [homebridge-rituals] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[4/24/2021, 6:00:59 PM] Got SIGTERM, shutting down Homebridge...

Even when I reinstall the plugin it gives me errors.

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-rituals@latest

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
[       ...........] / extract:homebridge-rituals: verb lock using /root/.npm/_locks/staging-d65aa1bb269289ee.lock for /homebridge/node_modules/.staging
![Schermafbeelding 2021-04-24 om 18 51 13](https://user-images.githubusercontent.com/73982879/115970035-48a20600-a540-11eb-9d86-4e208923508e.png)

**Comment by marked80** [comment]
Ok..... it seems someone just changed the Rituals password when ordering some new stuff.
After changing the password in the config file all worked fine again.
