### ISSUE TITLE
error version 1.1.2

### ISSUE THREAD

**Issue by PaulBartelings** [myluna08/homebridge-rituals#5]
Hi there,

I update from you prevues version that works perfectly, but now I get this error.

I use one Genie,

6-7-2020 21:38:41 Loaded plugin "homebridge-rituals".
6-7-2020 21:38:42 ReferenceError: key is not defined
    at /hoobs/node_modules/homebridge-rituals/index.js:162:30
    at Object.parseBody (/hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/hoobs/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/hoobs/node_modules/request-json/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/hoobs/node_modules/request-json/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
6-7-2020 21:38:42 Got SIGTERM, shutting down Bridge...

Hope you can help me ?

**Comment by myluna08** [comment]
Hi Paul, Update to 1.1.3 that corrects your issue.
Please confirm that works fine with this version.

**Comment by RobVerhoeven00** [comment]
It now works again....
