### ISSUE TITLE
Rituals Server Error causes Homebridge to "Crash"

### ISSUE THREAD

**Issue by Christian-CFP** [myluna08/homebridge-rituals#9]
Hey,
the Rituals server was temporarily down today.
In this state of unavailable to connect to the server, your plugin causes the whole Homebridge to malfunction.
The log was something with genie error 500 and the applications tab in Homebridge does not load.

Every Homekit device from Homebridge was not available in Homekit anymore!

So can you check on youre code? Its terrible if the Genie Server is down and Homebridge does not work anymore in Homekit.

**Comment by myluna08** [comment]
Dear Friend,
Nice to hear you again. Ok I will check.

**Comment by Christian-CFP** [comment]
NOW, the server is down once again. Test it!

`1.10.2020, 09:23:43 [Genie Wohnzimmer] Genie Wohnzimmer :: ERROR :: api/account/hubs :: getHub() > Error: connect ECONNREFUSED 46.22.190.75:443
1.10.2020, 09:23:43 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:161:92
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
1.10.2020, 09:23:43 [Genie Zoe] Genie Zoe :: ERROR :: api/account/hubs :: getHub() > Error: connect ECONNREFUSED 46.22.190.75:443
1.10.2020, 09:23:43 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:161:92
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
1.10.2020, 09:23:43 [Genie Nuria] Genie Nuria :: ERROR :: api/account/hubs :: getHub() > Error: connect ECONNREFUSED 46.22.190.75:443
1.10.2020, 09:23:43 TypeError: Cannot read property 'statusCode' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-rituals/index.js:161:92
    at Object.parseBody (/home/hoobs/.hoobs/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/hoobs/.hoobs/node_modules/request-json/main.js:148:26)
    at self.callback (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/hoobs/.hoobs/node_modules/request-json/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
1.10.2020, 09:23:43 Got SIGTERM, shutting down Bridge...`

**Comment by myluna08** [comment]
Dear friend,
Published a new version 1.1.9 with this kind of error controls. Many thanks for your patience and your testing.
